sudo: required
services:
  - docker

before_install:
  - docker build -t jjsheridan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jjsheridan/react-test npm test -- --coverage

after_success:
  - docker bulid -t jjsheridan/multi-client ./client
  - docker build -t jjsherida/multi-nginx ./nginx
  - docker build -t jjsheridan/multi-server ./server
  - docker build -t jjsheridan/multi-worker ./worker
  
  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jjsheridan/multi-client
  - docker push jjsheridan/multi-nginx
  - docker push jjsheridan/multi-server
  - docker push jjsheridan/multi-worker
